install.packages("tidyverse")
install.packages("readr")
install.packages("skimr")
install.packages("lubridate")
install.packages("janitor")
library(tidyverse)
library(readr)
library(skimr)
library(lubridate)
library(janitor)

dailyActivity <- read_csv("FitBit Fitness Tracker Data Set/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv")
heartrate_seconds <- read_csv("FitBit Fitness Tracker Data Set/Fitabase Data 4.12.16-5.12.16/heartrate_seconds_merged.csv")
